
local click_binding = {}

click_binding.keyCommands = {
    ----- start Left Front Panel -----
    
    {  down = click_cmds.PNT_500,  cockpit_device_id = devices.WCS, value_down = 0.0,
       name = _(cmd_names.PNT_500.." - OFF"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_500,  cockpit_device_id = devices.WCS, value_down = 0.333,
       name = _(cmd_names.PNT_500.." - BOMB"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_500,  cockpit_device_id = devices.WCS, value_down = 0.667,
       name = _(cmd_names.PNT_500.." - IR"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_500,  cockpit_device_id = devices.WCS, value_down = 1.0,
       name = _(cmd_names.PNT_500.." - GUN"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_501, up = click_cmds.PNT_501,  cockpit_device_id = devices.GEAR, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_501), category = {_('Lights')} },
    {  down = click_cmds.PNT_505,  cockpit_device_id = devices.GEAR, value_down = 0.0,
       name = _(cmd_names.PNT_505.." - Down"), category = {_('Systems')} },
    {  down = click_cmds.PNT_505,  cockpit_device_id = devices.GEAR, value_down = 1.0,
       name = _(cmd_names.PNT_505.." - Up"), category = {_('Systems')} },

    {  down = click_cmds.PNT_506,  cockpit_device_id = devices.SMS, value_down = 0.0,
       name = _(cmd_names.PNT_506.." - OFF"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_506,  cockpit_device_id = devices.SMS, value_down = 1.0,
       name = _(cmd_names.PNT_506.." - ON"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_507,  cockpit_device_id = devices.SMS, value_down = 0.0,
       name = _(cmd_names.PNT_507.." - Close"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_507,  cockpit_device_id = devices.SMS, value_down = 1.0,
       name = _(cmd_names.PNT_507.." - Open"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_508, up = click_cmds.PNT_508,  cockpit_device_id = devices.SMS, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_508), category = {_('Weapons')} },

    {  down = click_cmds.PNT_509,  cockpit_device_id = devices.WCS, value_down = 0.0,
       name = _(cmd_names.PNT_509.." - OFF"), category = {_('Weapons')} },
    {  down = click_cmds.PNT_509,  cockpit_device_id = devices.WCS, value_down = 1.0,
       name = _(cmd_names.PNT_509.." - ON"), category = {_('Weapons')} },
    
    ----- end Left Front sections -----
    ----- start LG Panel -----
    
    {  down = click_cmds.PNT_510,  cockpit_device_id = devices.GEAR, value_down = -1.0,
       name = _(cmd_names.PNT_510.." - OFF"), category = {_('Systems')} },
    {  down = click_cmds.PNT_510,  cockpit_device_id = devices.GEAR, value_down = 0.0,
       name = _(cmd_names.PNT_510.." - ON"), category = {_('Systems')} },
    {  down = click_cmds.PNT_510,  cockpit_device_id = devices.GEAR, value_down = 1.0,
       name = _(cmd_names.PNT_510.." - TEST"), category = {_('Systems')} },
    {  down = click_cmds.PNT_511,  cockpit_device_id = devices.GEAR, value_down = -1.0,
       name = _(cmd_names.PNT_511.." - NORM"), category = {_('Systems')} },
    {  down = click_cmds.PNT_511,  cockpit_device_id = devices.GEAR, value_down = 1.0,
       name = _(cmd_names.PNT_511.." - PARK"), category = {_('Systems')} },
    {  down = click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_down = -1.0,
       name = _(cmd_names.PNT_512.." - LDG"), category = {_('Lights')} },
    {  down = click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_down = 0.0,
       name = _(cmd_names.PNT_512.." - OFF"), category = {_('Lights')} },
    {  down = click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_down = 1.0,
       name = _(cmd_names.PNT_512.." - TAXI"), category = {_('Lights')} },

    {  down = click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_down = -1.0,
       name = _(cmd_names.PNT_513.." - DOWN"), category = {_('FCS')} },
    {  down = click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_513.." - STOP"), category = {_('FCS')} },
    {  down = click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_513.." - UP"), category = {_('FCS')} },
    
    ----- end LG sections -----
    ----- start Fuel Panel -----
    
    {  down = click_cmds.PNT_518,  cockpit_device_id = devices.FUEL, value_down = 0.0,
       name = _(cmd_names.PNT_518.." - OFF"), category = {_('Fuel')} },
    {  down = click_cmds.PNT_518,  cockpit_device_id = devices.FUEL, value_down = 1.0,
       name = _(cmd_names.PNT_518.." - ON"), category = {_('Fuel')} },
    
    ----- end Fuel sections -----
    ----- start Engine/Throttle sections -----

    {  down = click_cmds.PNT_571, up = click_cmds.PNT_571,  cockpit_device_id = devices.ENGINE, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_571), category = {_('Engine')} },
    {  down = click_cmds.PNT_572, up = click_cmds.PNT_572,  cockpit_device_id = devices.ENGINE, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_572), category = {_('Engine')} },
       
    {  down = click_cmds.PNT_519,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_519.." - OFF"), category = {_('Engine')} },
    {  down = click_cmds.PNT_519,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_519.." - ON"), category = {_('Engine')} },
    {  down = click_cmds.PNT_520,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_520.." - OFF"), category = {_('Engine')} },
    {  down = click_cmds.PNT_520,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_520.." - ON"), category = {_('Engine')} },
    {  down = click_cmds.PNT_521, up = click_cmds.PNT_521,  cockpit_device_id = devices.ENGINE, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_521), category = {_('Engine')} },
    {  down = click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_down = -1.0,
       name = _(cmd_names.PNT_522.." - TRG"), category = {_('Engine')} },
    {  down = click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_522.." - C+T"), category = {_('Engine')} },
    {  down = click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_522.." - CMBT"), category = {_('Engine')} },
    {  down = click_cmds.PNT_523,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_523.." - OFF"), category = {_('Engine')} },
    {  down = click_cmds.PNT_523,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_523.." - ON"), category = {_('Engine')} },
    {  down = click_cmds.PNT_524,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_524.." - OFF"), category = {_('Engine')} },
    {  down = click_cmds.PNT_524,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_524.." - ON"), category = {_('Engine')} },
    {  down = click_cmds.PNT_525,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_525.." - OFF"), category = {_('Engine')} },
    {  down = click_cmds.PNT_525,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_525.." - ON"), category = {_('Engine')} },
    {  down = click_cmds.PNT_526,  cockpit_device_id = devices.ENGINE, value_down = -1.0,
       name = _(cmd_names.PNT_526.." : COLD ENG"), category = {_('Engine')} },
    {  down = click_cmds.PNT_526,  cockpit_device_id = devices.ENGINE, value_down = 0.0,
       name = _(cmd_names.PNT_526.." : START"), category = {_('Engine')} },
    {  down = click_cmds.PNT_526,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
       name = _(cmd_names.PNT_526.." : COLD STARTER"), category = {_('Engine')} },

    ----- end Engine/Throttle sections -----
    ----- start FCS Panel -----
    
    {  down = click_cmds.PNT_527,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_527.." - OFF"), category = {_('FCS')} },
    {  down = click_cmds.PNT_527,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_527.." - ON"), category = {_('FCS')} },
    {  down = click_cmds.PNT_528,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_528.." - AUTO"), category = {_('FCS')} },
    {  down = click_cmds.PNT_528,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_528.." - EFCS"), category = {_('FCS')} },
    {  down = click_cmds.PNT_529,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_529.." - AUTO"), category = {_('FCS')} },
    {  down = click_cmds.PNT_529,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_529.." - R/Y AUG"), category = {_('FCS')} },
    {  down = click_cmds.PNT_530,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_530.." - OFF"), category = {_('FCS')} },
    {  down = click_cmds.PNT_530,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_530.." - ON"), category = {_('FCS')} },
    {  down = click_cmds.PNT_531,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_531.." - Pushdown"), category = {_('FCS')} },

-- elements["PNT_532"] = default_2_way_spring_switch(_(cmd_names.PNT_532),  devices.FCS, click_cmds.PNT_532, 532) -- YAW配平
    {  down = click_cmds.PNT_532, up = click_cmds.PNT_532,  cockpit_device_id = devices.FCS, value_down = -1.0, value_up = 0.0,
       name = _(cmd_names.PNT_532.." - Left"), category = {_('FCS')} },
    {  down = click_cmds.PNT_532, up = click_cmds.PNT_532,  cockpit_device_id = devices.FCS, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_532.." - Right"), category = {_('FCS')} },
    {  down = click_cmds.PNT_544,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_544), category = {_('FCS')} },
    {  down = click_cmds.PNT_535,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_535.." - A/G2"), category = {_('FCS')} },
    {  down = click_cmds.PNT_535,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_535.." - A/G1"), category = {_('FCS')} },
    {  down = click_cmds.PNT_536,  cockpit_device_id = devices.FCS, value_down = 0.0,
       name = _(cmd_names.PNT_536.." - A/G"), category = {_('FCS')} },
    {  down = click_cmds.PNT_536,  cockpit_device_id = devices.FCS, value_down = 1.0,
       name = _(cmd_names.PNT_536.." - A/A"), category = {_('FCS')} },
    
    ----- end FCS Panel -----
    ----- start Misc Panel -----

    {  down = click_cmds.PNT_537,  cockpit_device_id = devices.MISC, value_down = 0.0,
       name = _(cmd_names.PNT_537.." - Close"), category = {_('Misc Panel')} },
    {  down = click_cmds.PNT_537,  cockpit_device_id = devices.MISC, value_down = 1.0,
       name = _(cmd_names.PNT_537.." - Open"), category = {_('Misc Panel')} },
       
    {  down = click_cmds.PNT_538, up = click_cmds.PNT_538,  cockpit_device_id = devices.MISC, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_538), category = {_('Misc Panel')} },
       
    {  down = click_cmds.PNT_539,  cockpit_device_id = devices.MISC, value_down = 0.0,
       name = _(cmd_names.PNT_539.." - OFF"), category = {_('Misc Panel')} },
    {  down = click_cmds.PNT_539,  cockpit_device_id = devices.MISC, value_down = 1.0,
       name = _(cmd_names.PNT_539.." - ON"), category = {_('Misc Panel')} },
       
    {  down = click_cmds.PNT_540,  cockpit_device_id = devices.MISC, value_down = 0.0,
       name = _(cmd_names.PNT_540.." - OFF"), category = {_('Misc Panel')} },
    {  down = click_cmds.PNT_540,  cockpit_device_id = devices.MISC, value_down = 1.0,
       name = _(cmd_names.PNT_540.." - ON"), category = {_('Misc Panel')} },

    {  down = click_cmds.PNT_541,  cockpit_device_id = devices.ZCP, value_down = 0.0,
       name = _(cmd_names.PNT_541.." - OFF"), category = {_('ZCP')} },
    {  down = click_cmds.PNT_541,  cockpit_device_id = devices.ZCP, value_down = 1.0,
       name = _(cmd_names.PNT_541.." - ON"), category = {_('ZCP')} },
    {  down = click_cmds.PNT_542,  cockpit_device_id = devices.ZCP, value_down = 0.0,
       name = _(cmd_names.PNT_542.." - Close"), category = {_('ZCP')} },
    {  down = click_cmds.PNT_542,  cockpit_device_id = devices.ZCP, value_down = 1.0,
       name = _(cmd_names.PNT_542.." - Open"), category = {_('ZCP')} },
    {  down = click_cmds.PNT_543, up = click_cmds.PNT_543,  cockpit_device_id = devices.ZCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_543), category = {_('ZCP')} },
    
    ----- end Misc Panel -----
    ----- start Radio Control Box -----
    
    {  down = click_cmds.PNT_546,  cockpit_device_id = devices.INTERCOM, value_down = 0.0,
       name = _(cmd_names.PNT_546.." - SQL"), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_546,  cockpit_device_id = devices.INTERCOM, value_down = 1.0,
       name = _(cmd_names.PNT_546.." - OFF"), category = {_('Radio Control Box')} },
       
    {  down = click_cmds.PNT_547,  cockpit_device_id = devices.INTERCOM, value_down = 0.0,
       name = _(cmd_names.PNT_547.." - OFF"), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_547,  cockpit_device_id = devices.INTERCOM, value_down = 0.2,
       name = _(cmd_names.PNT_547.." - TR"), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_547,  cockpit_device_id = devices.INTERCOM, value_down = 0.4,
       name = _(cmd_names.PNT_547.." - TR+G"), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_547,  cockpit_device_id = devices.INTERCOM, value_down = 0.6,
       name = _(cmd_names.PNT_547.." - ADF"), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_547,  cockpit_device_id = devices.INTERCOM, value_down = 0.8,
       name = _(cmd_names.PNT_547.." - GD"), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_547,  cockpit_device_id = devices.INTERCOM, value_down = 1.0,
       name = _(cmd_names.PNT_547.." - SET"), category = {_('Radio Control Box')} },
       
    {  down = click_cmds.PNT_548, up = click_cmds.PNT_548,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_548), category = {_('Radio Control Box')} },
       
    {  down = click_cmds.PNT_549, up = click_cmds.PNT_549,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_549), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_550, up = click_cmds.PNT_550,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_550), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_551, up = click_cmds.PNT_551,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_551), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_552, up = click_cmds.PNT_552,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_552), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_553, up = click_cmds.PNT_553,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_553), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_554, up = click_cmds.PNT_554,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_554), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_555, up = click_cmds.PNT_555,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_555), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_556, up = click_cmds.PNT_556,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_556), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_557, up = click_cmds.PNT_557,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_557), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_558, up = click_cmds.PNT_558,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_558), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_559, up = click_cmds.PNT_559,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_559), category = {_('Radio Control Box')} },
    {  down = click_cmds.PNT_560, up = click_cmds.PNT_560,  cockpit_device_id = devices.INTERCOM, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_560), category = {_('Radio Control Box')} },
    
    ----- end Radio Control Box -----
    ----- start AAP sections -----
    
    {  down = click_cmds.PNT_911, up = click_cmds.PNT_911,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_911), category = {_('AAP')} },
    -- {  down = click_cmds.PNT_912, up = click_cmds.PNT_912,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_912), category = {_('AAP')} },
    -- {  down = click_cmds.PNT_913, up = click_cmds.PNT_913,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_913), category = {_('AAP')} },
    -- {  down = click_cmds.PNT_914, up = click_cmds.PNT_914,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_914), category = {_('AAP')} },
    {  down = click_cmds.PNT_915, up = click_cmds.PNT_915,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_915), category = {_('AAP')} },
    {  down = click_cmds.PNT_916, up = click_cmds.PNT_916,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_916), category = {_('AAP')} },
    {  down = click_cmds.PNT_917, up = click_cmds.PNT_917,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_917), category = {_('AAP')} },
    {  down = click_cmds.PNT_918, up = click_cmds.PNT_918,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_918), category = {_('AAP')} },
    {  down = click_cmds.PNT_919, up = click_cmds.PNT_919,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_919), category = {_('AAP')} },
    {  down = click_cmds.PNT_920, up = click_cmds.PNT_920,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_920), category = {_('AAP')} },
    {  down = click_cmds.PNT_921, up = click_cmds.PNT_921,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_921), category = {_('AAP')} },
    {  down = click_cmds.PNT_922, up = click_cmds.PNT_922,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_922), category = {_('AAP')} },
    {  down = click_cmds.PNT_923, up = click_cmds.PNT_923,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_923), category = {_('AAP')} },
    {  down = click_cmds.PNT_924, up = click_cmds.PNT_924,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_924), category = {_('AAP')} },
    {  down = click_cmds.PNT_925, up = click_cmds.PNT_925,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_925), category = {_('AAP')} },
    {  down = click_cmds.PNT_926, up = click_cmds.PNT_926,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_926), category = {_('AAP')} },
    {  down = click_cmds.PNT_927, up = click_cmds.PNT_927,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_927), category = {_('AAP')} },
    {  down = click_cmds.PNT_928, up = click_cmds.PNT_928,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_928), category = {_('AAP')} },
    {  down = click_cmds.PNT_929, up = click_cmds.PNT_929,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_929), category = {_('AAP')} },
    {  down = click_cmds.PNT_930, up = click_cmds.PNT_930,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_930), category = {_('AAP')} },
    {  down = click_cmds.PNT_931, up = click_cmds.PNT_931,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_931), category = {_('AAP')} },
    {  down = click_cmds.PNT_932, up = click_cmds.PNT_932,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_932), category = {_('AAP')} },
    {  down = click_cmds.PNT_933, up = click_cmds.PNT_933,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_933), category = {_('AAP')} },
    
    ----- end AAP sections -----
    ----- start ACP sections -----
    
    {  down = click_cmds.PNT_933, up = click_cmds.PNT_933,  cockpit_device_id = devices.AAP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_933), category = {_('ACP')} },
    
    ----- end ACP sections -----
    ----- start MFCD sections -----
    
    --- Left MFCD
    {  down = click_cmds.PNT_734, up = click_cmds.PNT_734,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_734), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_735, up = click_cmds.PNT_735,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_735), category = {_('MFCD Left')} },
       
    {  down = click_cmds.PNT_736, up = click_cmds.PNT_736,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_736), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_737, up = click_cmds.PNT_737,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_737), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_738, up = click_cmds.PNT_738,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_738), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_739, up = click_cmds.PNT_739,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_739), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_740, up = click_cmds.PNT_740,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_740), category = {_('MFCD Left')} },

    {  down = click_cmds.PNT_742, up = click_cmds.PNT_742,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_742), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_743, up = click_cmds.PNT_743,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_743), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_744, up = click_cmds.PNT_744,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_744), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_745, up = click_cmds.PNT_745,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_745), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_746, up = click_cmds.PNT_746,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_746), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_747, up = click_cmds.PNT_747,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_747), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_748, up = click_cmds.PNT_748,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_748), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_749, up = click_cmds.PNT_749,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_749), category = {_('MFCD Left')} },

    {  down = click_cmds.PNT_750, up = click_cmds.PNT_750,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_750), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_751, up = click_cmds.PNT_751,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_751), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_752, up = click_cmds.PNT_752,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_752), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_753, up = click_cmds.PNT_753,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_753), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_754, up = click_cmds.PNT_754,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_754), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_755, up = click_cmds.PNT_755,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_755), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_756, up = click_cmds.PNT_756,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_756), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_757, up = click_cmds.PNT_757,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_757), category = {_('MFCD Left')} },
       
    {  down = click_cmds.PNT_758, up = click_cmds.PNT_758,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_758), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_759, up = click_cmds.PNT_759,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_759), category = {_('MFCD Left')} },

    {  down = click_cmds.PNT_760, up = click_cmds.PNT_760,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_760), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_761, up = click_cmds.PNT_761,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_761), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_762, up = click_cmds.PNT_762,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_762), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_763, up = click_cmds.PNT_763,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_763), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_764, up = click_cmds.PNT_764,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_764), category = {_('MFCD Left')} },

    {  down = click_cmds.PNT_765, up = click_cmds.PNT_765,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_765), category = {_('MFCD Left')} },
    {  down = click_cmds.PNT_766, up = click_cmds.PNT_766,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_766), category = {_('MFCD Left')} },

    --- Center MFCD
    {  down = click_cmds.PNT_767, up = click_cmds.PNT_767,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_767), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_768, up = click_cmds.PNT_768,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_768), category = {_('MFCD Center')} },
       
    {  down = click_cmds.PNT_769, up = click_cmds.PNT_769,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_769), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_770, up = click_cmds.PNT_770,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_770), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_771, up = click_cmds.PNT_771,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_771), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_772, up = click_cmds.PNT_772,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_772), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_773, up = click_cmds.PNT_773,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_773), category = {_('MFCD Center')} },

    {  down = click_cmds.PNT_775, up = click_cmds.PNT_775,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_775), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_776, up = click_cmds.PNT_776,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_776), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_777, up = click_cmds.PNT_777,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_777), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_778, up = click_cmds.PNT_778,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_778), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_779, up = click_cmds.PNT_779,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_779), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_780, up = click_cmds.PNT_780,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_780), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_781, up = click_cmds.PNT_781,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_781), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_782, up = click_cmds.PNT_782,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_782), category = {_('MFCD Center')} },

    {  down = click_cmds.PNT_783, up = click_cmds.PNT_783,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_783), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_784, up = click_cmds.PNT_784,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_784), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_785, up = click_cmds.PNT_785,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_785), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_786, up = click_cmds.PNT_786,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_786), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_787, up = click_cmds.PNT_787,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_787), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_788, up = click_cmds.PNT_788,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_788), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_789, up = click_cmds.PNT_789,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_789), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_790, up = click_cmds.PNT_790,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_790), category = {_('MFCD Center')} },
       
    {  down = click_cmds.PNT_791, up = click_cmds.PNT_791,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_791), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_792, up = click_cmds.PNT_792,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_792), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_793, up = click_cmds.PNT_793,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_793), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_794, up = click_cmds.PNT_794,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_794), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_795, up = click_cmds.PNT_795,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_795), category = {_('MFCD Center')} },

    {  down = click_cmds.PNT_796, up = click_cmds.PNT_796,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_796), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_797, up = click_cmds.PNT_797,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_797), category = {_('MFCD Center')} },

    {  down = click_cmds.PNT_798, up = click_cmds.PNT_798,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_798), category = {_('MFCD Center')} },
    {  down = click_cmds.PNT_799, up = click_cmds.PNT_799,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_799), category = {_('MFCD Center')} },

    --- Right MFCD
    {  down = click_cmds.PNT_800, up = click_cmds.PNT_800,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_800), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_801, up = click_cmds.PNT_801,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_801), category = {_('MFCD Right')} },
       
    {  down = click_cmds.PNT_802, up = click_cmds.PNT_802,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_802), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_803, up = click_cmds.PNT_803,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_803), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_804, up = click_cmds.PNT_804,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_804), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_805, up = click_cmds.PNT_805,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_805), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_806, up = click_cmds.PNT_806,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_806), category = {_('MFCD Right')} },

    {  down = click_cmds.PNT_808, up = click_cmds.PNT_808,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_808), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_809, up = click_cmds.PNT_809,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_809), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_810, up = click_cmds.PNT_810,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_810), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_811, up = click_cmds.PNT_811,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_811), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_812, up = click_cmds.PNT_812,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_812), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_813, up = click_cmds.PNT_813,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_813), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_814, up = click_cmds.PNT_814,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_814), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_815, up = click_cmds.PNT_815,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_815), category = {_('MFCD Right')} },

    {  down = click_cmds.PNT_816, up = click_cmds.PNT_816,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_816), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_817, up = click_cmds.PNT_817,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_817), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_818, up = click_cmds.PNT_818,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_818), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_819, up = click_cmds.PNT_819,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_819), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_820, up = click_cmds.PNT_820,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_820), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_821, up = click_cmds.PNT_821,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_821), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_822, up = click_cmds.PNT_822,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_822), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_823, up = click_cmds.PNT_823,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_823), category = {_('MFCD Right')} },
       
    {  down = click_cmds.PNT_824, up = click_cmds.PNT_824,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_824), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_825, up = click_cmds.PNT_825,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_825), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_826, up = click_cmds.PNT_826,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_826), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_827, up = click_cmds.PNT_827,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_827), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_828, up = click_cmds.PNT_828,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_828), category = {_('MFCD Right')} },

    {  down = click_cmds.PNT_829, up = click_cmds.PNT_829,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_829), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_830, up = click_cmds.PNT_830,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_830), category = {_('MFCD Right')} },

    {  down = click_cmds.PNT_831, up = click_cmds.PNT_831,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_831), category = {_('MFCD Right')} },
    {  down = click_cmds.PNT_832, up = click_cmds.PNT_832,  cockpit_device_id = devices.MFCD, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_832), category = {_('MFCD Right')} },
    
    ----- end MFCD sections
    ----- start UFCP sections -----
    
    {  down = click_cmds.PNT_700, up = click_cmds.PNT_700,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_700), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_701, up = click_cmds.PNT_701,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_701), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_702, up = click_cmds.PNT_702,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_702), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_703, up = click_cmds.PNT_703,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_703), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_704, up = click_cmds.PNT_704,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_704), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_705, up = click_cmds.PNT_705,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_705), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_706, up = click_cmds.PNT_706,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_706), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_707, up = click_cmds.PNT_707,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_707), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_708, up = click_cmds.PNT_708,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_708), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_709, up = click_cmds.PNT_709,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_709), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_710, up = click_cmds.PNT_710,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_710), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_711, up = click_cmds.PNT_711,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_711), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_712, up = click_cmds.PNT_712,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_712), category = {_('UFCP')} },
    {  down = click_cmds.PNT_713, up = click_cmds.PNT_713,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_713), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_714, up = click_cmds.PNT_714,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_714), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_715, up = click_cmds.PNT_715,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_715), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_716, up = click_cmds.PNT_716,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_716), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_717, up = click_cmds.PNT_717,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_717), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_718, up = click_cmds.PNT_718,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_718), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_719, up = click_cmds.PNT_719,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_719), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_720, up = click_cmds.PNT_720,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_720), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_721, up = click_cmds.PNT_721,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_721), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_722, up = click_cmds.PNT_722,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_722), category = {_('UFCP')} }, 
    -- {  down = click_cmds.PNT_723, up = click_cmds.PNT_723,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_723), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_724, up = click_cmds.PNT_724,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_724), category = {_('UFCP')} }, 
    {  down = click_cmds.PNT_725, up = click_cmds.PNT_725,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       name = _(cmd_names.PNT_725), category = {_('UFCP')} }, 
    -- {  down = click_cmds.PNT_726, up = click_cmds.PNT_726,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_726), category = {_('UFCP')} }, 
    -- {  down = click_cmds.PNT_727, up = click_cmds.PNT_727,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_727), category = {_('UFCP')} }, 
 
    -- {  down = click_cmds.PNT_728, up = click_cmds.PNT_728,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_728), category = {_('UFCP')} }, 
    -- {  down = click_cmds.PNT_729, up = click_cmds.PNT_729,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_729), category = {_('UFCP')} }, 
    -- {  down = click_cmds.PNT_730, up = click_cmds.PNT_730,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_730), category = {_('UFCP')} }, 
    -- {  down = click_cmds.PNT_731, up = click_cmds.PNT_731,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_731), category = {_('UFCP')} },  
    -- {  down = click_cmds.PNT_732, up = click_cmds.PNT_732,  cockpit_device_id = devices.UFCP, value_down = 1.0, value_up = 0.0,
       -- name = _(cmd_names.PNT_732), category = {_('UFCP')} },
       
    ----- end UFCP sections
	-------- Special for Joysticks 
	
		--Special "Landing Gear Lever"
	{  down = click_cmds.PNT_505,  cockpit_device_id = devices.GEAR, value_down = 1.0,
	   up	= click_cmds.PNT_505,  cockpit_device_id = devices.GEAR, value_up	= 0.0,
       name = _(cmd_names.PNT_505.." - Up/Down"), category = {_('Special For Joystick'),_('Systems')} },
	 
	--Special  "Weapon Master Arm Switch"
	{  down = click_cmds.PNT_509,  cockpit_device_id = devices.WCS, value_down	= 1.0,
	   up	= click_cmds.PNT_509,  cockpit_device_id = devices.WCS, value_up	= 0.0,
       name = _(cmd_names.PNT_509.." - ARM/OFF"), category = {_('Special For Joystick'),_('Weapons')} },
	{  down = click_cmds.PNT_509,  cockpit_device_id = devices.WCS, value_down	= -1.0,
	   up	= click_cmds.PNT_509,  cockpit_device_id = devices.WCS, value_up	= 0.0,
       name = _(cmd_names.PNT_509.." - SIM/OFF"), category = {_('Special For Joystick'),_('Weapons')} },
	
	--Special "Brake Park/Norm",
	{  down = click_cmds.PNT_511,  cockpit_device_id = devices.GEAR, value_down	= 1.0,
	   up	= click_cmds.PNT_511,  cockpit_device_id = devices.GEAR, value_up	= -1.0,
       name = _(cmd_names.PNT_511..""), category = {_('Special For Joystick'),_('Systems')} },


	--Special "Light Switch - Land/Off/Taxi",
    {  down = click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_down = 1.0,
	   up	= click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_up   = 0.0,
       name = _(cmd_names.PNT_512.." - TAXI/OFF"), category = {_('Special For Joystick'),_('Lights')} },
    {  down = click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_down = -1.0,
	   up	= click_cmds.PNT_512,  cockpit_device_id = devices.LIGHTS, value_up   = 0.0,
       name = _(cmd_names.PNT_512.." - LDG/OFF"), category = {_('Special For Joystick'),_('Lights')} },

    
	--Special "Flap Switch - Up/Down",
	{  down = click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_down = 1.0,
	   up	= click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_up   = 0.0,
       name = _(cmd_names.PNT_513.." - UP/STOP"), category = {_('Special For Joystick'),_('FCS')} },
	{  down = click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_down = -1.0,
	   up	= click_cmds.PNT_513,  cockpit_device_id = devices.FCS, value_up   = 0.0,
       name = _(cmd_names.PNT_513.." - DOWN/STOP"), category = {_('Special For Joystick'),_('FCS')} },	   
	   
    
	--Special "Fuel Pump Switch",
	{  down = click_cmds.PNT_518,  cockpit_device_id = devices.FUEL, value_down	= 1.0,
	   up	= click_cmds.PNT_518,  cockpit_device_id = devices.FUEL, value_up	= 0.0,
       name = _(cmd_names.PNT_518.." - ON/OFF"), category = {_('Special For Joystick'),_('Fuel')} },
	   
	--Special "Throttle Cage/UnCage", ---  Need a proper name for this function. Currently only "Idle->Cutoff" or "Cutoff->Idle"
	{  down = click_cmds.PNT_572,  cockpit_device_id = devices.ENGINE, value_down	= 1.0,
	   up	= click_cmds.PNT_571,  cockpit_device_id = devices.ENGINE, value_up	= 1.0,
       name = _(cmd_names.PNT_571.." Lever - Cage/UnCage"), category = {_('Special For Joystick'),_('Engine')} },

	--Special "Engine Mode Switch",
	{  down = click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_down = -1.0,
	   up	= click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_up   = 0.0,
       name = _(cmd_names.PNT_522.." - TRG/C+T"), category = {_('Special For Joystick'),_('Engine')} },
	{  down = click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_down = 1.0,
	   up	= click_cmds.PNT_522,  cockpit_device_id = devices.ENGINE, value_up   = 0.0,
       name = _(cmd_names.PNT_522.." - CMBT/C+T"), category = {_('Special For Joystick'),_('Engine')} },   
	   
	--Special "Afterburner Switch",
	{  down = click_cmds.PNT_524,  cockpit_device_id = devices.ENGINE, value_down	= 1.0,
	   up	= click_cmds.PNT_524,  cockpit_device_id = devices.ENGINE, value_up	= 0.0,
       name = _(cmd_names.PNT_524.." - ON/OFF"), category = {_('Special For Joystick'),_('Engine')} },
	   
	--Special "HUD Backup Reticle Knob",  -- Use Switch replace for axis.
	{  down = click_cmds.PNT_731, cockpit_device_id = devices.UFCP, value_down = 1.0,
	   name = _(cmd_names.PNT_731.." - MAX"), category = {_('Special For Joystick'),_('UFCP')} },  
	{  down = click_cmds.PNT_731, cockpit_device_id = devices.UFCP, value_down = 0.0,
	   name = _(cmd_names.PNT_731.." - OFF"), category = {_('Special For Joystick'),_('UFCP')} },  

	--Special "UFC - +/,/- Switch", 
	{  down = click_cmds.PNT_730,  cockpit_device_id = devices.UFCP, value_down = 1.0,
	   up	= click_cmds.PNT_730,  cockpit_device_id = devices.UFCP, value_up   = 0.0,
       name = _(cmd_names.PNT_730.." - Down/CENTER"), category = {_('Special For Joystick'),_('UFC')} },
	{  down = click_cmds.PNT_730,  cockpit_device_id = devices.UFCP, value_down = -1.0,
	   up	= click_cmds.PNT_730,  cockpit_device_id = devices.UFCP, value_up   = 0.0,
       name = _(cmd_names.PNT_730.." - UP/CENTER"), category = {_('Special For Joystick'),_('UFC')} },   
	   
	--Special "HOTAS_Throttle_T1", 
	{  down = key_cmds.HOTAS_Throttle_T1_Forward,  --cockpit_device_id = devices.UFCP, value_down = 1.0,
	   up	= key_cmds.HOTAS_Throttle_T1_Center,  --cockpit_device_id = devices.UFCP, value_up   = 0.0,
       name = _(cmd_names.HOTAS_Throttle_T1_Forward.." / NAV"), category = {_('Special For Joystick'),_('HOTAS')} },
	{  down = key_cmds.HOTAS_Throttle_T1_Backward,  --cockpit_device_id = devices.UFCP, value_down = -1.0,
	   up	= key_cmds.HOTAS_Throttle_T1_Center,  --cockpit_device_id = devices.UFCP, value_up   = 0.0,
       name = _(cmd_names.HOTAS_Throttle_T1_Backward.." / NAV"), category = {_('Special For Joystick'),_('HOTAS')} },   
	 

}

return click_binding
